### ISSUE TITLE
Hpp file line 153 TIMER should be TIMER4

### ISSUE THREAD

**Issue by LaurentR59** [khoih-prog/Dx_Slow_PWM#2]
### Describe the bug

Hpp file line 153 TIMER should be TIMER4

### Steps to Reproduce

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

### Expected behavior

need to change TIMER3 TIMER4

### Actual behavior

TIMER4 defined incorreclty (define as TIMER3 again)

### Debug and AT-command log (if applicable)

set TIMER4

### Screenshots

N/A

### Information

Please ensure to specify the following:

N/A

### Additional context

N/A

**Comment by khoih-prog** [comment]
I couldn't find it, maybe already fixed before. Only unimportant message to change from TCB3 to TCB4 is

https://github.com/khoih-prog/Dx_Slow_PWM/blob/fd340604528a7073d8d38792d2f4cbee02e5056f/src/Dx_Slow_PWM.hpp#L162

Did you update to the latest version v1.0.1?
