### ISSUE TITLE
on exemples comment typo error on header file name must be changed by #include "Dx_Slow_PWM.h"

### ISSUE THREAD

**Issue by LaurentR59** [khoih-prog/Dx_Slow_PWM#3]
### Describe the bug

Not correct information on file name description

### Steps to Reproduce

bad comment typo

### Expected behavior

line 23 in comment swap #include "megaAVR_Slow_PWM.h" by #include "Dx_Slow_PWM.h".

### Actual behavior

N/A

### Debug and AT-command log (if applicable)

N/A

### Screenshots

N/A

### Information

N/A

### Additional context

N/A

**Comment by khoih-prog** [comment]
Thanks. This will be fixed in next release.

**Comment by khoih-prog** [comment]
Done..

---

### Release v1.0.2

1. Minor cosmetic fix
