### ISSUE TITLE
on exemples PWM_DutyCycle[] comment typo need to set [0;99] percentage

### ISSUE THREAD

**Issue by LaurentR59** [khoih-prog/Dx_Slow_PWM#4]
### Describe the bug

Comment is

// You can assign any interval for any timer here, in Microseconds
float PWM_DutyCycle[] =
...

May be should be described like for a defined freqency (juste before this step)  set the duty cycle according to value range [0;99] (or 100) 
(add comment like duty cycle manage light itensity level on an avarage Vout on the define frequzency)
adjust frequency to avoid flikering
adjust ducty cycle for intensity (Vout average)

### Steps to Reproduce

N/A

### Expected behavior

N/A

MAy be need to precise that some step are requird to use a channel

0 define inital settings
1/ define pin
2/ set frequency
3/ set duty cycle

### Actual behavior

N/A

### Debug and AT-command log (if applicable)

N/A

**Comment by khoih-prog** [comment]
I expect the users using this PWM library are more sophisticated, and don't need so many detailed, baby-step instructions. 
The basic `frequency, duty-cycle, initialization` must be known and mastered before using / designing **PWM-related hardware / firmware**.

I don't think I have enough time to explain everything to everybody.

Moreover, this **PWM** library can be used for many other applications, besides `LED Lighting`.

So, I won't go your way. But if you're willing to write a separate application note, I'll include it in the library.

Just let me know.

I'm closing the issue now as I won't spend time on this. 

Thanks anyway.
